const businessTitle = {
    1:[
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 12,
            "page_sort": true,
            "field": "operation",
            "field_name": "操作",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": false,
            "search_display": false,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 1,
            "field": "id",
            "field_name": "NO.",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 7,
            "page_sort": true,
            "field": 'business',
            "field_name": "业态名",
            "page_display": true,
            "edit_display": true,
            "edit_required": true,
            "edit_change": true,
            "search_display": true,
            "page_data_source":null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 6,
            "lower_layer": 0,
            "field": "abbreviation",
            "field_name": "简写",
            "page_display": true,
            "edit_display": true,
            "edit_required": true,
            "edit_change": true,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 12,
            "page_sort": true,
            "field": "theme",
            "field_name": "主题",
            "page_display": true,
            "edit_display": true,
            "edit_required": true,
            "edit_change": true,
            "search_display": false,
            "page_data_source": {
                "form_type": "color"
            },
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 7,
            "lower_layer": 0,
            "field": "feishu_app_id",
            "field_name": "飞书自建应用的app id",
            "page_display": true,
            "edit_display": true,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 8,
            "lower_layer": 0,
            "field": "feishu_app_secret",
            "field_name": "飞书自建应用的app secret",
            "page_display": true,
            "edit_display": true,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 9,
            "lower_layer": 0,
            "field": "feishu_departments_id",
            "field_name": "飞书一级部门id",
            "page_display": true,
            "edit_display": true,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 10,
            "lower_layer": 0,
            "field": "business_config",
            "field_name": "业态配置",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": true,
            "search_display": false,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 10,
            "lower_layer": 0,
            "field": "create_time",
            "field_name": "创建时间",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": false,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 11,
            "lower_layer": 0,
            "field": "update_time",
            "field_name": "更新时间",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": false,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },  
    
    ],
    2:[
        {
            "layer": 2,
            "block": 1,
            "types": 1,
            "sorting": 1,
            "page_sort": true,
            "field": "operation",
            "field_name": "操作",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": false,
            "search_display": false,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 2,
            "block": 1,
            "types": 1,
            "sorting": 2,
            "field": "id",
            "field_name": "NO.",
            "page_display": true,
            "edit_display": false,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "data_source": null,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 2,
            "block": 1,
            "types": 1,
            "sorting": 3,
            "field": "name",
            "field_name": "名称",
            "page_display": true,
            "edit_display": true,
            "edit_required": true,
            "edit_change": true,
            "search_display": true,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 2,
            "block": 1,
            "types": 1,
            "sorting": 4,
            "field": "environment",
            "field_name": "环境",
            "page_display": true,
            "edit_display": true,
            "edit_required": true,
            "edit_change": true,
            "search_display": true,
            "page_data_source": {
                "default_value": "默认环境",
            },
            "field_explain": null
        },
        {
            "layer": 2,
            "block": 1,
            "types": 1,
            "sorting": 5,
            "field": "key",
            "field_name": "Key",
            "page_display": true,
            "edit_display": true,
            "edit_required": true,
            "edit_change": true,
            "search_display": true,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 2,
            "block": 1,
            "types": 1,
            "sorting": 6,
            "field": "value",
            "field_name": "Value",
            "page_display": true,
            "edit_display": true,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "page_data_source": null,
            "field_explain": null
        },
        {
            "layer": 1,
            "block": 1,
            "types": 1,
            "sorting": 7,
            "field": "custom_data",
            "field_name": "自定义数据",
            "page_display": true,
            "edit_display": true,
            "edit_required": false,
            "edit_change": true,
            "search_display": true,
            "page_data_source": {
                "form_type": "json"
            },
            "field_explain": null
        }, 
    ]
};


export default businessTitle;
