import systemConfig from "@/config/index";


let menu = [
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 1,
        "field": "sorting",
        "field_name": "排序",
        "page_display": true,
        "page_sort": 1,
        "edit_display": false,
        "edit_required": false,
        "edit_change": true,
        "search_display": true,
        "page_data_source": null,
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 2,
        "field": "id",
        "field_name": "NO.",
        "page_display": true,
        "page_sort": 1,
        "edit_display": false,
        "edit_required": false,
        "edit_change": true,
        "search_display": true,
        "page_data_source": null,
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 5,
        "field": "level_2",
        "field_name": "一级菜单",
        "page_display": true,
        "edit_display": true,
        "edit_required": true,
        "edit_change": true,
        "search_display": true,
        "page_sort": true,
        "page_data_source": {
            "url": "manage/menus/list/0",
            "value": "id",
            "label": "menu_name",
            "data_source": "url",
            "children_field":"menu_name",
            "need_slots": true,
        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 3,
        "lower_layer": 0,
        "field": "menu_name",
        "field_name": "二级菜单",
        "page_display": true,
        "page_sort": true,
        "edit_display": true,
        "edit_required": true,
        "edit_change": true,
        "search_display": true,
        "page_data_source": null,
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 4,
        "lower_layer": 0,
        "field": "level_1",
        "field_name": "一级菜单",
        "page_display": false,
        "edit_display": false,
        "edit_required": false,
        "edit_change": false,
        "search_display": true,
        "page_sort": true,
        "page_data_source": null,
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 5,
        "lower_layer": 0,
        "field": "menu_group",
        "field_name": "菜单组",
        "page_display": true,
        "page_sort": true,
        "edit_display": true,
        "edit_required": true,
        "edit_change": true,
        "search_display": true,
        "page_data_source": {
            "data_source": "data",
            "data": systemConfig.MENU_GROUP,
        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 6,
        "field": "icon",
        "field_name": "图标",
        "page_display": true,
        "edit_display": true,
        "edit_required": false,
        "edit_change": true,
        "search_display": true,
        "page_sort": true,
        "page_data_source": {
            "children_field":"vue_url",
            "need_slots": true,
        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 7,
        "page_sort": true,
        "field": "permissions_url",
        "field_name": "权限URL",
        "page_display": true,
        "edit_display": true,
        "edit_required": true,
        "edit_change": true,
        "search_display": true,
        "page_data_source": {
            "form_type": "select",
            "multiple": "tags"

        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 8,
        "field": "vue_url",
        "field_name": "页面URL",
        "page_display": true,
        "edit_display": true,
        "edit_required": true,
        "edit_change": true,
        "search_display": true,
        "page_data_source": null,
        "page_sort": true,
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 9,
        "page_sort": true,
        "field": "menu_describe",
        "field_name": "菜单描述",
        "page_display": true,
        "edit_display": true,
        "edit_required": false,
        "edit_change": true,
        "search_display": true,
        "page_data_source": null,
        "field_explain": null
    },

    /*     {

        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 10,
        "page_sort": true,
        "field": "env_data_status",
        "field_name": "环境权限 ",
        "page_display": true,
        "edit_display": true,
        "edit_required": false,
        "edit_change": true,
        "search_display": false,
        "page_data_source": {
            "form_type": "boole"
        },
        "field_explain": null
    }, */
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 11,
        "page_sort": true,
        "field": "status",
        "field_name": "是否上线",
        "page_display": false,
        "edit_display": true,
        "edit_required": false,
        "edit_change": true,
        "search_display": false,
        "page_data_source": {
            "form_type": "boole",
            
        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 11,
        "page_sort": true,
        "field": "page_display",
        "field_name": "是否显示",
        "page_display": true,
        "edit_display": true,
        "edit_required": false,
        "edit_change": true,
        "search_display": false,
        "page_data_source": {
            "form_type": "boole",
        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 11,
        "page_sort": true,
        "field": "page_data_source",
        "field_name": "数据源",
        "page_display": true,
        "edit_display": true,
        "edit_required": false,
        "edit_change": true,
        "search_display": false,
        "page_data_source": {
            "form_type": "json",
        },
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 12,
        "page_sort": true,
        "field": "operation",
        "field_name": "操作",
        "page_display": true,
        "edit_display": false,
        "edit_required": false,
        "edit_change": false,
        "search_display": false,
        "page_data_source": null,
        "field_explain": null
    },
    {
        "layer": 1,
        "block": 1,
        "types": 1,
        "sorting": 13,
        "page_sort": true,
        "field": "title",
        "field_name": "Title配置",
        "page_display": true,
        "edit_display": false,
        "edit_required": false,
        "edit_change": false,
        "search_display": false,
        "page_data_source": null,
        "field_explain": null
    }
];
export default menu;
